name: EchoWebapp

on:
  push:
    branches: [ main ]
    paths:
      - 'echo-webapp/**'
      - '.github/workflows/echo-webapp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'echo-webapp/**'
      - '.github/workflows/echo-webapp.yml'

env:
  AZURE_WEBAPP_NAME: "tbernardo-echo-app"
  ARTIFACT_NAME: "echo-webapp"

permissions:
  id-token: write
  contents: read
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v2
    #   with:
    #     dotnet-version: 6.0.x
    # - name: Restore dependencies
    #   run: |
    #     dotnet restore echo-webapp/echo-webapp.csproj
    
    # - name: Build
    #   run: |
    #     dotnet build --no-restore echo-webapp/echo-webapp.csproj -c Release

    - uses: ./.github/workflows/composite/build-dotnet #tasb/my-public-actions/build-dotnet@main
      with:
        dotnetProject: 'echo-webapp/echo-webapp.csproj'
        buildConfiguration: Release
    
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish --no-build echo-webapp/echo-webapp.csproj -c Release -o echo-webapp/publish

    - uses: actions/upload-artifact@v3
      if: github.event_name != 'pull_request'
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: echo-webapp/publish

  prod:
    if: github.event_name != 'pull_request'
    
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./${{ env.ARTIFACT_NAME }}
    
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  

    - name: 'Azure webapp deploy - PROD'
      id: prod-deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        package: ./${{ env.ARTIFACT_NAME }}
        slot-name: 'production'

    - name: logout
      run: |
        az logout